[[redirects]]
  from = "/"
  to = "/cn/"
  status = 301
  force = true
  conditions = {Country = ["CN","HK"], Language = ["en"]}
  # conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}